CREATE DATABASE smartcity_db;
USE smartcity_db;

CREATE TABLE user (
userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
username VARCHAR(60) NOT NULL, 
email VARCHAR(100) NOT NULL, 
password VARCHAR(500) NOT NULL,
userType VARCHAR(20) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE city (
cityId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
state VARCHAR(10) NOT NULL,
latitude DECIMAL(20, 10) NOT NULL,
longitude DECIMAL(20, 10) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE publicTrans (
publicTransId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
description VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE event (
eventId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT,
name VARCHAR(500) NOT NULL,
description VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE industries (
industriesId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
industryType VARCHAR(500) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE mall (
mallId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE park (
parkId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE restaurant (
restaurantId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE museum (
museumId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE library (
libraryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE zoo (
zooId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE hotel (
hotelId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE college (
collegeId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(500) NOT NULL,
address VARCHAR(500) NOT NULL, 
departments VARCHAR(500) NOT NULL, 
email VARCHAR(500) NOT NULL,
image VARCHAR(1000) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_db.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;