# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('postcode', models.IntegerField()),
                ('state', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('industry_type', models.CharField(max_length=100)),
                ('item_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('postcode', models.IntegerField()),
                ('state', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('user_type', models.IntegerField()),
            ],
        ),
    ]
