# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, null=True)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
