# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_events_library_publictrans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictrans',
            name='image',
        ),
    ]
