# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_remove_publictrans_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publictrans',
            old_name='number',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='publictrans',
            name='update',
        ),
    ]
