# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
