# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_hotel_industries_malls_museum_park_restaurant_zoo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Malls',
            new_name='Mall',
        ),
    ]
