# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_auto_20171012_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='publictrans',
            name='city',
        ),
    ]
