# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_locationinfo_infotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationinfo',
            name='infoType',
            field=models.CharField(choices=[('0', 'College'), ('3', 'Hotel'), ('2', 'Indusry'), ('1', 'Library'), ('8', 'Mall'), ('6', 'Museum'), ('4', 'Park'), ('7', 'Restaurant'), ('5', 'Zoo')], max_length=1, null=True),
        ),
    ]
