# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_auto_20171015_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.LocationInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Profile')),
            ],
        ),
    ]
